env:
  - CGO_ENABLED=0
before:
  hooks:
    - make coverage
builds:
- skip: true
release:
  gitlab:
    owner: damianoneill
    name: net
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
