# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go get -u github.com/mattn/goveralls
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0

script:
  - ./bin/golangci-lint run
  - go test -v -timeout 120s -race  $(go list github.com/damianoneill/net/v2/... | grep -v testserver) -coverprofile=coverage.out # Run all the tests with the race detector enabled
  - goveralls -coverprofile=coverage.out -service travis-ci
